name: Update OSINT Data

on:
  schedule:
    - cron: "0 * * * *"   # Каждый час
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run parser
        run: node parser.js

      - name: Commit updated data
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add data/data.json
          git commit -m "Auto update data" || echo "No changes"
          git push

